# Generated by Django 5.0.4 on 2024-05-06 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='cocuntry',
            new_name='country',
        ),
    ]
